#! /usr/bin/env bash

# Author:       Arturo Aguilar Lagunas
# Date:         Sat Apr 23 08:30:45 AM CDT 2022
# Description:  Startup for awesome wm

$HOME/.homemade/bin/system/set-custom-hardware-settings
$HOME/.homemade/bin/init-my-system-stuff
$HOME/.homemade/bin/daemons/acpi-battery-popup-alert &
$HOME/.homemade/bin/daemons/lock-on-lid-closed &
# $HOME/.config/conky/launch.sh
# killall conky

# dunst
picom
