#!/bin/bash
# Author: 	Arturo Aguilar Lagunas
# Description:	Install python packages

# Info
echo "Installing packages from .pip-packages file"

# Variables
packages=$(<pip-packages)
# Installing packages
for package in $packages
do
	echo ""
	echo "Installing: $package"
	pip install $package
done

# Notes
echo ""
echo "Notes:"
echo "      - Tested in Ubuntu 18.04 LTS"
echo "Done"
